name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Bash commands
        run: |
          echo "Running Bash commands..."
          # Your Bash commands here
          mkdir my_directory
          echo "Hello, World!" > my_directory/hello.txt
          cat my_directory/hello.txt
